#!/bin/zsh
# Run for login shells
# after: /etc/zshenv ~/.zshenv /etc/zprofile ~/.zprofile /etc/zshrc ~/.zshrc /etc/zlogin
# (http://zsh.sourceforge.net/Guide/zshguide02.html#l9)

typeset -U path

export EDITOR=vim
export MJM_HOST=`hostname -s | sed -e 's/[0-9]*$//'`

if [[ -d /usr/workspace/martymcf ]]; then
  export MJM_WS=/usr/workspace/martymcf
else
  export MJM_WS=$HOME
fi

export MJM_SCRATCH=$MJM_WS    # Default value
case "$MJM_HOST" in
  rzalastor)
    export MJM_SCRATCH=/p/lustre1/martymcf
    ;;
  rzansel)
    export MJM_SCRATCH=/p/gpfs1/martymcf
    ;;
  rzgenie)
    export MJM_SCRATCH=/p/lustre1/martymcf
    ;;
  rzmanta)
    export MJM_SCRATCH=/p/gscratchrzm/martymcf
    ;;
  rztopaz)
    export MJM_SCRATCH=/p/lustre1/martymcf
    ;;
  rztrona)
    export MJM_SCRATCH=/p/lustre1/martymcf
    ;;
  rzuseq)
    export MJM_SCRATCH=/p/lustre1/martymcf
    ;;
  cztb)
    export MJM_SCRATCH=/home/martymcf
    ;;
  *)
    if [[ -d /usr/workspace/martymcf ]]; then
      export MJM_SCRATCH=/usr/workspace/martymcf
    else
      export MJM_SCRATCH=$HOME
    fi
    ;;
esac

export MJM_SOURCEDIR=$MJM_WS/src
mkdir -p $MJM_SOURCEDIR

if [[ -d $HOME/.bin ]]; then
  path=( $HOME/.bin $path )
fi

export SPACK_ROOT=$MJM_WS/spack
if [[ -d $SPACK_ROOT/bin ]]; then
  if [[ $MJM_HOST != rzcrayz ]]; then
    . $SPACK_ROOT/share/spack/setup-env.sh
    path=( $SPACK_ROOT/bin $path )
  fi
fi

if (( ${+SYS_TYPE} )); then 
  export MJM_ARCH=$SYS_TYPE
else
  if [[ -f $HOME/.mydotfiles/.arch_cache/$MJM_HOST ]]; then
    export MJM_ARCH=`cat $HOME/.mydotfiles/.arch_cache/$MJM_HOST`
  else
    if [[ -d $SPACK_ROOT/bin ]]; then
      $SPACK_ROOT/bin/spack arch > $HOME/.mydotfiles/.arch_cache/$MJM_HOST
      export MJM_ARCH=`cat $HOME/.mydotfiles/.arch_cache/$MJM_HOST`
    else
      export MJM_ARCH=`uname -m`
    fi
  fi
fi

if [[ -f $HOME/.mydotfiles/.arch_cache/modules.$MJM_HOST ]]; then
  source $HOME/.mydotfiles/.arch_cache/modules.$MJM_HOST
fi

if (( ${+SYS_TYPE} )); then 
  module list
else
  export PMIX_MCA_gds=hash
fi

cds
