#!/bin/zsh
# Run for interactive shells
# after: /etc/zshenv ~/.zshenv /etc/zprofile ~/.zprofile /etc/zshrc
# (http://zsh.sourceforge.net/Guide/zshguide02.html#l9)

# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' max-errors 3
zstyle :compinstall filename '/Users/loki/.zshrc'

autoload -Uz compinit
compinit

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.mydotfiles/zsh/oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="apple"

# ZSH_THEME="3den"
# ZSH_THEME="Soliah"
# ZSH_THEME="adben"
# ZSH_THEME="af-magic"
# ZSH_THEME="afowler"
# ZSH_THEME="agnoster"
# ZSH_THEME="alanpeabody"
# ZSH_THEME="amuse"
# ZSH_THEME="apple"
# ZSH_THEME="arrow"
# ZSH_THEME="aussiegeek"
# ZSH_THEME="avit"
# ZSH_THEME="awesomepanda"
# ZSH_THEME="bira"
# ZSH_THEME="blinks"
# ZSH_THEME="bureau"
# ZSH_THEME="candy-kingdom"
# ZSH_THEME="candy"
# ZSH_THEME="clean"
# ZSH_THEME="cloud"
# ZSH_THEME="crcandy"
# ZSH_THEME="crunch"
# ZSH_THEME="cypher"
# ZSH_THEME="dallas"
# ZSH_THEME="darkblood"
# ZSH_THEME="daveverwer"
# ZSH_THEME="dieter"
# ZSH_THEME="dogenpunk"
# ZSH_THEME="dpoggi"
# ZSH_THEME="dst"
# ZSH_THEME="dstufft"
# ZSH_THEME="duellj"
# ZSH_THEME="eastwood"
# ZSH_THEME="edvardm"
# ZSH_THEME="emotty"
# ZSH_THEME="essembeh"
# ZSH_THEME="evan"
# ZSH_THEME="fino-time"
# ZSH_THEME="fino"
# ZSH_THEME="fishy"
# ZSH_THEME="flazz"
# ZSH_THEME="fletcherm"
# ZSH_THEME="fox"
# ZSH_THEME="frisk"
# ZSH_THEME="frontcube"
# ZSH_THEME="funky"
# ZSH_THEME="fwalch"
# ZSH_THEME="gallifrey"
# ZSH_THEME="gallois"
# ZSH_THEME="garyblessington"
# ZSH_THEME="gentoo"
# ZSH_THEME="geoffgarside"
# ZSH_THEME="gianu"
# ZSH_THEME="gnzh"
# ZSH_THEME="gozilla"
# ZSH_THEME="half-life"
# ZSH_THEME="humza"
# ZSH_THEME="imajes"
# ZSH_THEME="intheloop"
# ZSH_THEME="itchy"
# ZSH_THEME="jaischeema"
# ZSH_THEME="jbergantine"
# ZSH_THEME="jispwoso"
# ZSH_THEME="jnrowe"
# ZSH_THEME="jonathan"
# ZSH_THEME="josh"
# ZSH_THEME="jreese"
# ZSH_THEME="jtriley"
# ZSH_THEME="juanghurtado"
# ZSH_THEME="junkfood"
# ZSH_THEME="kafeitu"
# ZSH_THEME="kardan"
# ZSH_THEME="kennethreitz"
# ZSH_THEME="kiwi"
# ZSH_THEME="kolo"
# ZSH_THEME="kphoen"
# ZSH_THEME="lambda"
# ZSH_THEME="linuxonly"
# ZSH_THEME="lukerandall"
# ZSH_THEME="macovsky-ruby"
# ZSH_THEME="macovsky"
# ZSH_THEME="maran"
# ZSH_THEME="mgutz"
# ZSH_THEME="mh"
# ZSH_THEME="michelebologna"
# ZSH_THEME="mikeh"
# ZSH_THEME="miloshadzic"
# ZSH_THEME="minimal"
# ZSH_THEME="mira"
# ZSH_THEME="mortalscumbag"
# ZSH_THEME="mrtazz"
# ZSH_THEME="murilasso"
# ZSH_THEME="muse"
# ZSH_THEME="nanotech"
# ZSH_THEME="nebirhos"
# ZSH_THEME="nicoulaj"
# ZSH_THEME="norm"
# ZSH_THEME="obraun"
# ZSH_THEME="peepcode"
# ZSH_THEME="philips"
# ZSH_THEME="pmcgee"
# ZSH_THEME="pygmalion-virtualenv"
# ZSH_THEME="pygmalion"
# ZSH_THEME="re5et"
# ZSH_THEME="refined"
# ZSH_THEME="rgm"
# ZSH_THEME="risto"
# ZSH_THEME="rixius"
# ZSH_THEME="rkj-repos"
# ZSH_THEME="rkj"
# ZSH_THEME="robbyrussell"
# ZSH_THEME="sammy"
# ZSH_THEME="simonoff"
# ZSH_THEME="simple"
# ZSH_THEME="skaro"
# ZSH_THEME="smt"
# ZSH_THEME="sonicradish"
# ZSH_THEME="sorin"
# ZSH_THEME="sporty_256"
# ZSH_THEME="steeef"
# ZSH_THEME="strug"
# ZSH_THEME="sunaku"
# ZSH_THEME="sunrise"
# ZSH_THEME="superjarin"
# ZSH_THEME="suvash"
# ZSH_THEME="takashiyoshida"
# ZSH_THEME="terminalparty"
# ZSH_THEME="theunraveler"
# ZSH_THEME="tjkirch"
# ZSH_THEME="tjkirch_mod"
# ZSH_THEME="tonotdo"
# ZSH_THEME="trapd00r"
# ZSH_THEME="wedisagree"
# ZSH_THEME="wezm+"
# ZSH_THEME="wezm"
# ZSH_THEME="wuffers"
# ZSH_THEME="xiong-chiamiov-plus"
# ZSH_THEME="xiong-chiamiov"
# ZSH_THEME="ys"
# ZSH_THEME="zhann"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
export ZSH_TMUX_ITERM2=true
plugins=(git colored-man-pages colorize dirpersist vi-mode battery iterm2 man themes tmux zsh_reload)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias a=alias
a D="ls -sF"
a f="pushd"
a b="popd"
a h="history"
a C="clear"
a J="jobs -l"
a less="less -X"
a tmux="tmux -u"
a vi=vim
a project="source ~/.mydotfiles/zsh/zsh_project"

HISTSIZE=100000000
SAVEHIST=100000000
HISTFILE=~/.zsh_history

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt NO_BEEP
setopt AUTO_CD

# source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# POWERLEVEL9K_MODE='nerdfont-complete'
# source  ~/powerlevel9k/powerlevel9k.zsh-theme
