#!/bin/bash
# Set up our global environment variables
#
export MJM_HOST=`hostname -s | sed -e "s/[0-9]*$//"`

if [[ $MJM_HOST == "rz"* ]]; then
  export MJM_WS=/usr/workspace/wsrzd/martymcf
elif [[ $MJM_HOST == "cztb" ]]; then
  export MJM_WS=/home/martymcf
else
  if [ -d /usr/workspace/wsb/martymcf ]; then
    export MJM_WS=/usr/workspace/wsb/martymcf
  else
    export MJM_WS=$HOME
  fi
fi

if [ ! -d $HOME/.mydotfiles/.arch_cache ]; then
  mkdir -p $HOME/.mydotfiles/.arch_cache
fi

if [ ! -f $HOME/.mydotfiles/.arch_cache/$MJM_HOST ]; then
  if [ -f $HOME/spack.$MJM_HOST/bin/spack ]; then
    $HOME/spack.$MJM_HOST/bin/spack arch > $HOME/.mydotfiles/.arch_cache/$MJM_HOST
  elif [ -f $HOME/spack/bin/spack ]; then
    $HOME/spack/bin/spack arch > $HOME/.mydotfiles/.arch_cache/$MJM_HOST
  else
    uname -m > $HOME/.mydotfiles/.arch_cache/$MJM_HOST
  fi
fi

export MJM_ARCH=`cat $HOME/.mydotfiles/.arch_cache/$MJM_HOST`

export MJM_BIN=$HOME/.bin/$MJM_ARCH

if [ -f $HOME/spack.$MJM_HOST/bin/spack ]; then
  export PATH=$HOME/spack.$MJM_HOST/bin:$PATH
elif [ -f $HOME/spack/bin/spack ]; then
  export PATH=$HOME/spack/bin:$PATH
fi

if [ -f /etc/toss-release ]; then
    MJM_TOSSVERSION=`cat /etc/toss-release`
    MJM_TOSSVERSION=${MJM_TOSSVERSION#*-}
    MJM_TOSSVERSION=${MJM_TOSSVERSION#*-}
    export MJM_TOSSVERSION=${MJM_TOSSVERSION%%.*}
else
    export MJM_TOSSVERSION=0
fi

if [ -d /nfs/tmp2/martymcf ]; then
  export TMP=/nfs/tmp2/martymcf
else
  export TMP=/tmp
fi

export TMPDIR=$TMP
export SSH_ASKPASS=""
export EDITOR=vim

export MJM_SESSION="No Project"

export INSTALLDIR=$HOME/.session/install/$MJM_ARCH/install
export INSTALLDIR2=$INSTALLDIR".2"
export BUILDDIR=$HOME/.session/build/$MJM_ARCH
export SRCDIR=$HOME/.session/src

function project {
  if [ -z ${1+x} ]; then 
    echo "Current Project is: " $MJM_SESSION
  else
    rm -f $HOME/.session
    mkdir -p $MJM_WS/$1/src $MJM_WS/$1/build/$MJM_ARCH $MJM_WS/$1/install/$MJM_ARCH/install $MJM_WS/$1/install/$MJM_ARCH/install2
    ln -s $MJM_WS/$1 $HOME/.session
    export MJM_SESSION=$1
  fi
}
