# Source global definitions
if [ -f $HOME/.mydotfiles/bashrc/.bashrc.global ]; then
    . $HOME/.mydotfiles/bashrc/.bashrc.global
fi

if [ -f $HOME/.mydotfiles/bashenv/rc.$MJM_ARCH ]; then
    . $HOME/.mydotfiles/bashenv/rc.$MJM_ARCH
fi

bmake() {
  bsub -Is -n 1 -R "span[ptile=1]" make $@
}

bcmd() {
  bsub -Is -n 1 -R "span[ptile=1]" $@
}

# if [ -f $HOME/.mydotfiles/hacks/bsub_path_hack.$MJM_HOST ]; then
  # . $HOME/.mydotfiles/hacks/bsub_path_hack.$MJM_HOST
# fi
